// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFAKS7FDfDK0eWhVeYiq4MCnowC9GEv-g',
    appId: '1:522016338025:web:d715e709b4bd5d5e9bf2f8',
    messagingSenderId: '522016338025',
    projectId: 'airosstorange',
    authDomain: 'airosstorange.firebaseapp.com',
    storageBucket: 'airosstorange.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BHvHX_eIwSKIHbzeSro-E_cuwEf2wGw',
    appId: '1:522016338025:android:fe3125135f3795829bf2f8',
    messagingSenderId: '522016338025',
    projectId: 'airosstorange',
    storageBucket: 'airosstorange.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADDny6DN236OOLBqn6-gVpwRlrApg8pxE',
    appId: '1:522016338025:ios:653460c6e9cda3509bf2f8',
    messagingSenderId: '522016338025',
    projectId: 'airosstorange',
    storageBucket: 'airosstorange.appspot.com',
    iosBundleId: 'labsoft.airosmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADDny6DN236OOLBqn6-gVpwRlrApg8pxE',
    appId: '1:522016338025:ios:4eb2de0aca9a33309bf2f8',
    messagingSenderId: '522016338025',
    projectId: 'airosstorange',
    storageBucket: 'airosstorange.appspot.com',
    iosBundleId: 'labsoft.airosmobile.RunnerTests',
  );
}
